import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class Test {
	
	public static void main(String[] args) {
			try {
				InputStream input = new FileInputStream("C:/aaa.txt");
				byte[] arr = new byte[10];
				
				input.read(arr);
				for (int i = 0; i < arr.length; i++) {
					System.out.print(arr[i] + " ");
				}
				System.out.println();
				
				input = new FileInputStream("C:/ddd.txt");
				input.read(arr);
				for (int i = 0; i < arr.length; i++) {
					System.out.print(arr[i] + " ");
				}
				System.out.println();
			} catch (IOException e) {
			// FileNotFoundException도 IOException을 상속하고 있기 때문에 try/catch 한 번만 작성해도 됨
				e.printStackTrace();
			}

		
	}
	
}